### model
model_name_or_path: /home/hao/CCFT/LLaMA-Factory/models/CCFT_havid_sub_videos_crop_balanced_lh_v0_ac_obj_2
adapter_name_or_path: /home/hao/CCFT/LLaMA-Factory/saves/Qwen2.5-VL-7B-Instruct/lora/best_models/25-06-2025/CCFT_havid_sub_videos_crop_balanced_lh_v0_tool_4_layer_more_pixels/checkpoint-700
template: qwen2_vl
finetuning_type: lora

### export
export_dir: /home/hao/CCFT/LLaMA-Factory/models/CCFT_havid_sub_videos_crop_balanced_lh_v0_full_2
export_size: 5
export_device: cpu
export_legacy_format: false